- name: This playbook will install, configure nginx as LB
  hosts: nginxlb
  become: yes
  tasks:
   - name: Install nginx web server
     apt: name=nginx state=latest update_cache=yes

   - name: Configure nginx web root folder
     copy: src=default-lb dest=/etc/nginx/nginx.conf 

   - name: Restart the Webserver
     command: service nginx restart
     
